### ISSUE TITLE
公式錯誤

### ISSUE THREAD

**Issue by bestpika** [bobby1030/taipower-light#1]
官方的公式寫的是
> `(系統運轉淨尖峰供電能力-系統瞬時尖峰負載(瞬間值))÷系統瞬時尖峰負載(瞬間值)×100%`

但是這個網頁的公式卻是拿`目前用電量`來計算
而且根本沒有什麼實時備轉容量率
這種寫法講得好像只要當時用電很低當日備轉就沒問題一樣

請修正謝謝

**Comment by bobby1030** [comment]
Hi,
根據我的理解，臺電的公式使用「尖峰」負載是表示當日尖峰時段的備轉容量率，
而本專案為了取得「實時」備轉容量率，使用「當前負載」來計算應該是對的？

**Comment by bestpika** [comment]
就我對備轉容量的理解，這樣有誤導的嫌疑。
因為發電不是台電隨時想要加開容量都可以，這台電早就解釋過了。

我上面也提了，這樣在離峰的時候看到的狀況就好像台灣沒有限電危機一樣。
如果這個網頁想要呈現即時的狀況，也請把當日的狀況一起顯示在上面。

**Comment by bobby1030** [comment]
我大概瞭解你的意思了
因為「備轉容量率」這個名詞應該是專用來衡量「當日尖峰的供電可靠度」，而不是實時的電力指標
這部份不知道有沒有更好的名詞來稱呼，如果沒有我可能會在網頁下方加上這部分的說明。

**Comment by bestpika** [comment]
好的，謝謝

**Comment by bobby1030** [comment]
現在已經在頁面下方加註說明，至於名詞的更改會再去詢問一些意見，感謝你的回報
https://github.com/bobby1030/taipower-light/commit/a4152f66b0dda8c01e51cae0555a531cd38f4abb

**Comment by chongyie** [comment]
經過多方收集資料，很明顯地備轉容量是用來評估電力系統當天還有多少儲備運轉空間。
而且還有許多地方根據需要會有各自的定義。甚至這些容量可以是用買的來作為當天的餘裕。

經過比對我國電力調度的專家GORDON CHENG的說明後，我想我們現在想要看的是某一段時間系統目前負載與實際可用供電能力的差距。

我國台電似乎沒有提供相關的定義，但從鄭先生的網站我建議使用這個名詞

剩餘容量率（remaining capacity ratio）= (可靠可用容量-負載)/可靠可用容量

鄭先生的網頁
https://gordoncheng.wordpress.com/2011/06/09/%E6%BC%AB%E8%AB%87%E5%82%99%E7%94%A8%E5%AE%B9%E9%87%8F%E8%88%87%E5%82%99%E8%BD%89%E5%AE%B9%E9%87%8F/

俄國所用的各種容量定義說明
http://www.gnedenko-forum.org/Journal/2015/012015/RTA_1_2015-06.pdf

**Comment by bobby1030** [comment]
參考 @chongyie 的意見，我在 ab7e543 中已經把這個數值的名稱改叫「實時剩餘容量率」
[計算公式](https://github.com/bobby1030/taipower-light/blob/ab7e5439f1ac83f0d934f2dae7c3602f92152087/index.html#L42:L45)更改為：

> (最大供電能力 - 目前用電量) / 最大供電能力

頁面下方註明[相關說明文字](https://github.com/bobby1030/taipower-light/blob/ab7e5439f1ac83f0d934f2dae7c3602f92152087/index.html#L25)

現在暫時把這個 issue 關掉，但若大家有其他建議也可以繼續提出。
